#!/usr/bin/env bash
# Installing Nginx on Server
sudo apt-get update -y && sudo apt-get upgrade -y
sudo apt-get install -y nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx restart
